-- ========================================================================
-- SIAP TANI: Seed Data for Crops & Market Baselines
-- ========================================================================

INSERT INTO public.crops (slug, name, category, description, growth_days_min, growth_days_max, water_requirement, water_requirement_mm, optimal_temp_min, optimal_temp_max, rainfall_min, rainfall_max, market_price_baseline)
VALUES
(
    'padi',
    'Padi Sawah (Oryza sativa)',
    'Pangan Utama',
    'Tanaman pangan utama dengan kebutuhan air tinggi dan sensitif terhadap cekaman kekeringan pada fase pembungaan.',
    105,
    120,
    'High',
    550,
    22,
    34,
    150,
    300,
    13500
),
(
    'jagung',
    'Jagung Hibrida (Zea mays)',
    'Palawija',
    'Tanaman palawija toleran kekeringan moderat, cocok sebagai rotasi tanaman setelah padi pada musim kemarau.',
    90,
    110,
    'Medium',
    380,
    21,
    32,
    80,
    180,
    6200
),
(
    'kedelai',
    'Kedelai (Glycine max)',
    'Kacang-kacangan',
    'Tanaman legum pengikat nitrogen tanah, ideal untuk perbaikan kesuburan lahan dan kebutuhan air sedang.',
    75,
    95,
    'Medium',
    320,
    20,
    30,
    70,
    150,
    11800
),
(
    'bawang-merah',
    'Bawang Merah (Allium cepa var. ascalonicum)',
    'Hortikultura',
    'Komoditas hortikultura bernilai ekonomi tinggi, rentan terhadap genangan air dan kelembapan berlebih.',
    55,
    70,
    'Medium',
    250,
    25,
    32,
    40,
    120,
    32000
),
(
    'cabai-merah',
    'Cabai Merah Keriting (Capsicum annuum)',
    'Hortikultura',
    'Tanaman sayuran buah dengan nilai fluktuasi harga tinggi, membutuhkan drainase tanah yang baik.',
    80,
    100,
    'Medium',
    350,
    22,
    30,
    60,
    150,
    42000
),
(
    'tomat',
    'Tomat (Solanum lycopersicum)',
    'Hortikultura',
    'Tanaman hortikultura berumur pendek, membutuhkan sinar matahari penuh dan suhu harian moderat.',
    65,
    85,
    'Medium',
    300,
    20,
    28,
    50,
    140,
    14000
),
(
    'kentang',
    'Kentang Dataran Tinggi (Solanum tuberosum)',
    'Hortikultura Umbi',
    'Tanaman umbi subtropis/dataran tinggi (>1000 mdpl), membutuhkan temperatur sejuk dan tanah gembur.',
    90,
    120,
    'High',
    420,
    15,
    22,
    80,
    180,
    16500
),
(
    'kacang-tanah',
    'Kacang Tanah (Arachis hypogaea)',
    'Palawija',
    'Tanaman polong toleran kekeringan, sangat baik untuk lahan kering dan rotasi pasca panen.',
    85,
    105,
    'Low',
    280,
    22,
    33,
    50,
    130,
    18500
),
(
    'tebu',
    'Tebu (Saccharum officinarum)',
    'Perkebunan Semusim',
    'Tanaman industri penghasil gula berumur panjang, membutuhkan periode kering sebelum panen untuk pembentukan sukrosa.',
    300,
    360,
    'High',
    800,
    24,
    35,
    100,
    250,
    4500
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    growth_days_min = EXCLUDED.growth_days_min,
    growth_days_max = EXCLUDED.growth_days_max,
    water_requirement_mm = EXCLUDED.water_requirement_mm,
    optimal_temp_min = EXCLUDED.optimal_temp_min,
    optimal_temp_max = EXCLUDED.optimal_temp_max,
    market_price_baseline = EXCLUDED.market_price_baseline;
